# Generated by Django 4.2.6 on 2023-11-15 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredientrecipe_amount_alter_recipe_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Некорректное значение. Минимум 1'), django.core.validators.MaxValueValidator(5000, message='Некорректное значение. Максимум 5000')], verbose_name='Число Ингредиентов'),
        ),
    ]
